import {
  siTypescript,
  siJavascript,
  siPython,
  siReact,
  siVite,
  siTailwindcss,
  siNodedotjs,
  siFastapi,
  siPostgresql,
  siGit,
  siDocker,
  siHtml5,
  siCss,
  siNextdotjs,
  siVuedotjs,
  siSvelte,
  siGraphql,
  siRedis,
  siMongodb,
  siMysql,
  siSqlite,
  siDjango,
  siFlask,
  siExpress,
  siGo,
  siRust,
  siPhp,
  siRubyonrails,
  siKubernetes,
  siGooglecloud,
  siVercel,
  siNetlify,
  siGithub,
  siGitlab,
  siFigma,
  siJest,
  siCypress,
  siWebpack,
  siPnpm,
  siYarn,
  siLinux,
  siGnubash,
  siSwift,
  siKotlin,
  siJquery,
  siJson,
  siMarkdown,
  siAngular,
  siBootstrap,
  siBitbucket,
  siJira,
  siRabbitmq,
  siStoryblok,
  type SimpleIcon,
} from 'simple-icons'

/** Maps a skill/tech label (case-insensitive) to its simple-icons glyph + brand color. */
const ICONS: Record<string, SimpleIcon> = {
  typescript: siTypescript,
  javascript: siJavascript,
  python: siPython,
  react: siReact,
  'react.js': siReact,
  vite: siVite,
  'tailwind css': siTailwindcss,
  tailwindcss: siTailwindcss,
  'node.js': siNodedotjs,
  nodejs: siNodedotjs,
  node: siNodedotjs,
  fastapi: siFastapi,
  postgresql: siPostgresql,
  postgres: siPostgresql,
  git: siGit,
  docker: siDocker,
  html: siHtml5,
  html5: siHtml5,
  css: siCss,
  css3: siCss,
  'next.js': siNextdotjs,
  nextjs: siNextdotjs,
  'vue.js': siVuedotjs,
  vue: siVuedotjs,
  svelte: siSvelte,
  graphql: siGraphql,
  redis: siRedis,
  mongodb: siMongodb,
  mongo: siMongodb,
  mysql: siMysql,
  sqlite: siSqlite,
  django: siDjango,
  flask: siFlask,
  express: siExpress,
  'express.js': siExpress,
  go: siGo,
  golang: siGo,
  rust: siRust,
  php: siPhp,
  'ruby on rails': siRubyonrails,
  rails: siRubyonrails,
  kubernetes: siKubernetes,
  k8s: siKubernetes,
  gcp: siGooglecloud,
  'google cloud': siGooglecloud,
  vercel: siVercel,
  netlify: siNetlify,
  github: siGithub,
  gitlab: siGitlab,
  figma: siFigma,
  jest: siJest,
  cypress: siCypress,
  webpack: siWebpack,
  pnpm: siPnpm,
  yarn: siYarn,
  linux: siLinux,
  bash: siGnubash,
  shell: siGnubash,
  swift: siSwift,
  kotlin: siKotlin,
  jquery: siJquery,
  json: siJson,
  markdown: siMarkdown,
  angular: siAngular,
  bootstrap: siBootstrap,
  bitbucket: siBitbucket,
  jira: siJira,
  rabbitmq: siRabbitmq,
  storyblok: siStoryblok,
}

export function getTechIcon(label: string): SimpleIcon | undefined {
  return ICONS[label.trim().toLowerCase()]
}
